### PR TITLE
Remove Thanos references

### PR DESCRIPTION
**Pull request by juandspy**

### CODE REVIEW

**Review by tisnik — APPROVED** [review]
ok, let's forget about our hard work on it

**Comment by juandspy** [comment]
> ok, let's forget about our hard work on it

Sorry about that :/

**Comment by joselsegura** [comment]
I think that, as long as we have cluster_thanos_info files in our storage, we should keep its reference, but obviously marking it as "deprecated" in the docs.

In a few months when the thanos info files are removed, we can go ahead and remove all the references to it

**Comment by juandspy** [comment]
> I think that, as long as we have cluster_thanos_info files in our storage, we should keep its reference, but obviously marking it as "deprecated" in the docs.
> 
> In a few months when the thanos info files are removed, we can go ahead and remove all the references to it

I'm going to delete those in a couple of hours :) https://issues.redhat.com/browse/CCXDEV-5115

**Comment by juandspy** [comment]
[CCXDEV-5115](https://issues.redhat.com/browse/CCXDEV-5115) done. Merging this.

**Pull request merged**
